### ISSUE TITLE
Alert not showing

### ISSUE THREAD

**Issue by yousefabuz17** [ItHertzSoGood/Altilium#1]
I am running on an iPhone XS Max on IOS 13.5

So far I have tried many battery percentages for testing and never received an alert for it. 

Great tweak by the way, I am looking forward on using it for when my battery hits 5%

**Comment by quiprr** [comment]
Hey there! Thanks for letting me know about this, and sorry for the wait.
To diagnose this issue, I would need a lot of help from you. If you're interested, please message me on Discord: quiprr#7412. Thanks!

**Comment by yousefabuz17** [comment]
Ok awesome I'm more than happy to help. I sent your a friend request. My username is yousefabuz17

**Comment by quiprr** [comment]
Talked in DM's
